@echo off
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\3vars.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\5vars.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\9sym_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\carry.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\con1f1.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\con2f2.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\exam1_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\exam3_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\max46_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\newill_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\newtag_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd53f1.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd53f2.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd53f3.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd73f1.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd73f2.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd73f3.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd84f1.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd84f2.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd84f3.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\rd84f4.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\sao2f1.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\sao2f2.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\sao2f3.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\sao2f4.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\sym10_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\t481_d.pla
java -cp build\classes MemristorsSOP.MemristorsSOP benchmarks\xor5_d.pla
