@echo off
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\3vars.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\5vars.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\9sym_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\carry.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\con1f1.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\con2f2.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\exam1_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\exam3_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\max46_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\newill_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\newtag_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f1.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f2.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f3.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f1.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f2.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f3.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f1.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f2.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f3.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f4.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f1.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f2.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f3.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f4.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sym10_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\t481_d.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\xor5_d.pla
