@echo off
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\3vars_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\5vars_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\9sym_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\carry_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\con1f1_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\con2f2_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\exam1_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\exam3_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\max46_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\newill_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\newtag_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f1_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f2_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd53f3_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f1_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f2_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd73f3_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f1_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f2_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f3_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\rd84f4_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f1_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f2_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f3_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sao2f4_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\sym10_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\t481_d_rondo.pla
java -cp build\classes MemristorsWM2.MemristorsWM2 benchmarks\xor5_d_rondo.pla
