rondo -q3 benchmarks\3vars.pla
rondo -q3 benchmarks\4vars.pla
rondo -q3 benchmarks\5vars.pla
rondo -q3 benchmarks\9sym_d.pla
rondo -q3 benchmarks\carry.pla
rondo -q3 benchmarks\con1f1.pla
rondo -q3 benchmarks\con2f2.pla
rondo -q3 benchmarks\exam1_d.pla
rondo -q3 benchmarks\exam3_d.pla
rondo -q3 benchmarks\life_d.pla
rondo -q3 benchmarks\max46_d.pla
rondo -q3 benchmarks\newill_d.pla
rondo -q3 benchmarks\newtag_d.pla
rondo -q3 benchmarks\rd53f1.pla
rondo -q3 benchmarks\rd53f2.pla
rondo -q3 benchmarks\rd53f3.pla
rondo -q3 benchmarks\rd73f1.pla
rondo -q3 benchmarks\rd73f2.pla
rondo -q3 benchmarks\rd73f3.pla
rondo -q3 benchmarks\rd84f1.pla
rondo -q3 benchmarks\rd84f2.pla
rondo -q3 benchmarks\rd84f3.pla
rondo -q3 benchmarks\rd84f4.pla
rondo -q3 benchmarks\sao2f1.pla
rondo -q3 benchmarks\sao2f2.pla
rondo -q3 benchmarks\sao2f3.pla
rondo -q3 benchmarks\sao2f4.pla
rondo -q3 benchmarks\sym10_d.pla
rondo -q3 benchmarks\t481_d.pla
rondo -q3 benchmarks\xor5_d.pla
