@echo off
java -cp build\classes ESOPCount.ESOPCount benchmarks\3vars.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\5vars.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\9sym_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\carry.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\con1f1.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\con2f2.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\exam1_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\exam3_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\max46_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\newill_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\newtag_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd53f1.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd53f2.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd53f3.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd73f1.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd73f2.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd73f3.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd84f1.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd84f2.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd84f3.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\rd84f4.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\sao2f1.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\sao2f2.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\sao2f3.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\sao2f4.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\sym10_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\t481_d.esop
java -cp build\classes ESOPCount.ESOPCount benchmarks\xor5_d.esop
