@echo off
java -cp build\classes SOPCount.SOPCount benchmarks\3vars_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\5vars_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\9sym_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\carry_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\con1f1_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\con2f2_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\exam1_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\exam3_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\max46_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\newill_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\newtag_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd53f1_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd53f2_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd53f3_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd73f1_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd73f2_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd73f3_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd84f1_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd84f2_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd84f3_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\rd84f4_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\sao2f1_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\sao2f2_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\sao2f3_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\sao2f4_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\sym10_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\t481_d_rondo.pla
java -cp build\classes SOPCount.SOPCount benchmarks\xor5_d_rondo.pla
